### ISSUE TITLE
希望可以增加添加全局公共请求参数的接口

### ISSUE THREAD

**Issue by for7GG** [senierr/RxHttp#2]
目前只能添加get公共请求参数，而且设置也不方便，只能在builder中设置，希望rxhttp中增加方法，添加公共请求参数后，无论什么类型的请求，都会使用公共参数

产生原因是App全局只使用一个rxhttp，不知道这样是否合适？

**Comment by senierr** [comment]
目前仅支持公共URL参数，对于公共请求体参数，可以考虑。

针对不同域，不推荐使用同一RxHttp实体，而是使用不同的RxHttp实体，并配置各自的参数。
